import unittest
import invert
import pickle

class TestDataIntegrity(unittest.TestCase):
    
    def test_data_integrity(self):
        print("Testing to ensure variables dumped by invert are correctly loaded")
        stopwords_list, data_list, url_list, title_list, description_list = invert.invert(testMode=True, testFilePath="test_files")
        # Load the vars generated by the invert script for use while searching
        with open('InvertVariableStore.pckl', 'rb') as loadable:
            stopwords_list2, data_list2, url_list2, title_list2, description_list2 = pickle.load(loadable)
        self.assertEqual(stopwords_list, stopwords_list2)
        self.assertEqual(data_list, data_list2)
        self.assertEqual(url_list, url_list2)
        self.assertEqual(title_list, title_list2)
        self.assertEqual(description_list, description_list2)
        
        

if __name__ == "__main__":
    unittest.main();